# docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # For development, you can uncomment the line below to mount your code
    # and see changes without rebuilding the image.
    # volumes:
    #   - .:/usr/src/app