services:
  - type: web
    name: arabic-miracle-backend
    env: python
    plan: free
    buildCommand: |
      # 1) Install Java (headless) for the JAR
      apt-get update && \
      apt-get install -y default-jdk-headless && \
      # 2) Install Python deps
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
